
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ACER/AppData/Local/Programs/Python/Python39/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Android - 1 - aarch64
      The host system is: Windows - 10.0.26100 - AMD64
...
